version: '3'

services:
  mariadb:
    image: mariadb:10.7.1-focal
    environment:
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=passwordasd123
      - MYSQL_ROOT_PASSWORD=passwordasd123
      - MYSQL_DATABASE=marcaje

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mariadb